In [1]:
import numpy as np

In [20]:
with open("data_1.txt") as f:
    numbers = f.read()

In [21]:
complete_list = []
temp_list = []
for number in numbers:
    if number == "\n":
        complete_list.append(temp_list)
        temp_list = []
    else:
        temp_list.append(int(number))
complete_list.append(temp_list)

matrix = np.array(complete_list)
print(matrix)



[[3 0 0 ... 2 1 1]
 [1 3 3 ... 0 3 0]
 [2 1 3 ... 1 3 3]
 ...
 [3 1 0 ... 1 2 1]
 [0 1 2 ... 2 3 0]
 [3 1 1 ... 0 2 2]]


In [22]:
visibles = 0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if i in (0, matrix.shape[0] - 1) or j in (0, matrix.shape[1] - 1):
            visibles += 1
            continue
        else:
            up_list = matrix[:i, j]
            rigth_list = matrix[i, j+1:]
            down_list = matrix[i+1:, j]
            left_list = matrix[i, :j]
            if matrix[i, j] > up_list.max() or matrix[i, j] > rigth_list.max() or matrix[i, j] > down_list.max() or matrix[i, j] > left_list.max():
                visibles += 1

print("visibles:", visibles)

visibles: 1717
